# Generated by Django 5.0.1 on 2024-08-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
