# Generated by Django 5.0.1 on 2024-08-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_order_orderitem_shippingaddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_orderd",
            new_name="date_ordered",
        ),
    ]
